UNIPROT_URL = "https://rest.uniprot.org/uniprotkb/search"
UNIPROT_LOGS="storage/uniprot"
LOGS="storage/logs"
ARTIFACTS="storage/artifacts"
FASTAS="storage/fastas"
IFEATURE="ml/data"
DB="ml/data"
MODEL="ml/models"